apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-role
  namespace: wardrobewiz
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-rolebinding
  namespace: wardrobewiz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-role
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-namespace-ingress-nginx
  namespace: wardrobewiz
spec:
  podSelector: {}  # Apply to all pods in the namespace
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
