apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: mailhog
spec:
  type: ClusterIP
  selector:
    app: mailhog
  ports:
    - name: ui
      port: 8025
      targetPort: 8025
    - name: smtp
      port: 1025
      targetPort: 1025