apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: microservicedesign.azurecr.io/cart
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_REDIS_HOST
              value: redis.wardrobewiz.svc.cluster.local
            - name: SPRING_REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: thai-acr
---

apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - port: 8888
      targetPort: 8888