apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image:  microservicedesign.azurecr.io/cart
          ports:
            - containerPort: 9292
          env:
            - name: SPRING_REDIS_HOST
              value: your-redis-host.default.svc.cluster.local
            - name: SPRING_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 9292
  type: LoadBalancer